const days=[
{date:'10.14',week:'수',city:'방콕',title:'안녕, 방콕',icon:'✈️',summary:'방콕 도착 → 카오산로드',events:[['09:35','인천 → 방콕 출발','Thai Airways TG659 · Airbus A350-900 예정 · 한국 현지 시간','h'],['13:25','수완나품공항 도착','TG659 · 방콕 현지 시간','h'],['14:30–16:00','입국 · 호텔 이동 · 체크인','숙소 미정'],['16:00–17:30','호텔에서 휴식','잠깐 쉬어가기'],['18:00','저녁 식사','식당 미정','food'],['19:30–22:30','카오산로드','거리 구경 · 길거리 음식 · 맥주','h'],['00:30','호텔 복귀','다음 날 새벽']]},
{date:'10.15',week:'목',city:'방콕',title:'사원에서 야시장까지',icon:'🛕',summary:'왕궁 → 강 건너 왓아룬 → 야오와랏 먹방',events:[['08:00','기상',''],['08:30','호텔 출발',''],['09:00–12:00','왕궁 + 왓 프라깨우 투어','오전 사원 탐방','h'],['12:00–13:00','점심 식사','식당 미정','food'],['13:00–14:00','휴식',''],['14:00–14:30','타띠엔 → 강 건너 왓아룬','보트 이동'],['14:30–17:30','왓아룬 관광','강변 사원 둘러보기','h'],['17:30–18:30','왓아룬 일몰 + 야경','관람 장소·당일 운영시간 확인 예정','h'],['18:30–19:00','차이나타운 이동','택시'],['19:00–23:00','야오와랏 먹방','저녁과 야식 · 식당 미정','h'],['00:30','호텔 복귀','다음 날 새벽']]},
{date:'10.16',week:'금',city:'방콕 → 파타야',title:'도시를 떠나, 바다로',icon:'🚐',summary:'아침 식사 → 체크아웃 → 파타야 이동',events:[['아침','아침 식사','식당 미정','food'],['09:00','체크아웃','짐 챙기기'],['09:30','방콕 → 파타야','이동편 미정','h'],['도착 후','파타야에서의 첫날','점심·저녁·숙소 및 세부 일정 미정']]},
{date:'10.17',week:'토',city:'파타야',title:'파타야, 하루의 여유',icon:'🏝️',summary:'바다 곁에서 보내는 하루',events:[['하루','파타야 일정','세부 일정은 아직 정하지 않았어요.','h'],['식사','아침 · 점심 · 저녁 · 야식','장소와 시간 미정','food']]},
{date:'10.18',week:'일',city:'파타야',title:'조금 더, 파타야',icon:'🌊',summary:'파타야에서 보내는 두 번째 온전한 하루',events:[['하루','파타야 일정','세부 일정은 아직 정하지 않았어요.','h'],['식사','아침 · 점심 · 저녁 · 야식','장소와 시간 미정','food']]},
{date:'10.19',week:'월',city:'파타야 → 방콕',title:'다시 만나는 방콕',icon:'🌃',summary:'방콕 복귀 → 카페와 휴식 → 저녁 → 루프탑',events:[['아침','파타야 → 방콕','이동편 미정','h'],['11:30–12:00','호텔 도착 · 짐 맡기기','숙소 미정'],['12:30','점심 식사','식당 미정','food'],['14:00','카페','장소 미정','food'],['15:30','디저트','장소 미정','food'],['16:30–18:00','호텔 휴식',''],['18:30','방콕 저녁 식사','식당 미정','food'],['20:30','루프탑 · 야경','장소 미정','h']]},
{date:'10.20',week:'화',city:'방콕 → 인천',title:'마지막까지, 방콕답게',icon:'🛍️',summary:'시암 쇼핑 → 카페 → 마지막 저녁 → 23:30 출국',events:[['09:30','기상',''],['10:30','브런치','식당 미정','food'],['11:30','체크아웃 · 짐 보관',''],['12:00–15:00','시암 → 센트럴월드 쇼핑','방콕에서의 마지막 쇼핑','h'],['15:00','카페','장소 미정','food'],['16:30','디저트','장소 미정','food'],['17:30','호텔 복귀 · 짐 찾기',''],['18:30','마지막 저녁','식당 미정','food'],['20:00','공항 이동','택시'],['21:00 전후','수완나품공항 도착','출국 준비'],['23:30','방콕 → 인천 출발','Thai Airways TG656 · Boeing 787-8 예정 · 방콕 현지 시간','h']]},
{date:'10.21',week:'수',city:'인천',title:'여행을 담아, 집으로',icon:'🇰🇷',summary:'06:55 인천 도착',events:[['06:55','인천공항 도착','Thai Airways TG656 · 10/20 출발편 · 한국 현지 시간','h']]}
];
let selected=0;const nav=document.querySelector('#days');let visits={};let storageOK=true;try{visits=JSON.parse(localStorage.getItem('thai-trip-visits')||'{}');if(!visits||typeof visits!=='object')visits={}}catch{storageOK=false;visits={}}
// Preserve completed visits when removed events shift the remaining event positions.
try{if(!localStorage.getItem('thai-trip-visits-v2')){
for(const [day,removed,last] of [[0,6,7],[1,10,11],[3,2,2],[4,2,2],[5,8,8]]){
for(let i=removed;i<last;i++){if(Object.prototype.hasOwnProperty.call(visits,`${day}-${i+1}`))visits[`${day}-${i}`]=visits[`${day}-${i+1}`];else delete visits[`${day}-${i}`]}
delete visits[`${day}-${last}`]}
localStorage.setItem('thai-trip-visits',JSON.stringify(visits));localStorage.setItem('thai-trip-visits-v2','1')
}}catch{storageOK=false}
const places=[[/인천.*출발|인천공항 도착/,'Incheon International Airport','인천국제공항 · ICN'],[/수완나품|방콕 → 인천 출발/,'Suvarnabhumi Airport','수완나품공항 · BKK'],[/카오산/,'Khao San Road Bangkok','Khao San Road'],[/왕궁/,'The Grand Palace Bangkok','The Grand Palace · Wat Phra Kaew'],[/타띠엔/,'Tha Tien Pier Bangkok','Tha Tien Pier'],[/왓아룬/,'Wat Arun Bangkok','Wat Arun'],[/야오와랏|차이나타운 이동/,'Yaowarat Road Bangkok','Yaowarat Road'],[/센트럴월드/,'centralwOrld Bangkok','Siam → centralwOrld']];
const notes=['방콕 도착 후에는 호텔에서 쉬어가요. 저녁에는 카오산로드를 둘러봐요.','왕궁에서 왓아룬, 야오와랏으로 이어지는 하루. 왓아룬 운영시간과 야경 관람 장소는 확인 예정이에요.','09:00 체크아웃 후 09:30 파타야로 출발해요. 이동편과 도착 후 일정은 미정입니다.','오늘은 파타야에서 보내는 하루. 식사와 관광 세부 일정은 아직 미정이에요.','파타야에서 여유롭게 보내는 마지막 하루. 다음 날 아침 방콕으로 돌아가요.','11:30–12:00 호텔에 짐을 맡긴 뒤, 식사와 카페를 즐겨요.','17:30 호텔에서 짐 찾기 → 20:00 공항 이동 → 23:30 TG656 출국.','06:55 인천 도착. 한국 현지 시간 기준입니다.'];
function type(e){if(e[3]==='food'||/먹방/.test(e[1]))return ['맛집','food'];if(/호텔|체크/.test(e[1]))return ['숙소',''];if(/공항|출발|이동|→/.test(e[1]))return ['이동',''];if(/기상|휴식/.test(e[1]))return ['휴식',''];return ['관광','']}
function place(e){return places.find(p=>p[0].test(e[1]))}
function progress(){const total=days[selected].events.length;const count=days[selected].events.filter((_,i)=>visits[`${selected}-${i}`]).length;document.querySelector('#progress-count').textContent=`${count} / ${total}`;document.querySelector('#progress').max=total;document.querySelector('#progress').value=count;document.querySelector('#storage-note').textContent=storageOK?'방문 체크는 이 기기에만 저장돼요.':'이 브라우저에서는 방문 체크를 저장할 수 없어요.'}
days.forEach((d,i)=>{const b=document.createElement('button');b.type='button';b.id=`day-tab-${i}`;b.setAttribute('role','tab');b.setAttribute('aria-controls','day-panel');b.innerHTML=`<span class="day-num">DAY ${String(i+1).padStart(2,'0')}</span><span class="date">${d.date}<span class="weekday">${d.week}</span></span><span class="location">${i===6?'귀국':i===7?'인천 도착':d.city.replace('방콕 → ','').replace('파타야 → ','')}</span>`;b.onclick=()=>render(i);b.onkeydown=e=>{let n;if(e.key==='ArrowRight')n=(i+1)%8;if(e.key==='ArrowLeft')n=(i+7)%8;if(e.key==='Home')n=0;if(e.key==='End')n=7;if(n!==undefined){e.preventDefault();render(n);nav.children[n].focus()}};nav.append(b)});
function render(index){selected=index;const d=days[index];[...nav.children].forEach((b,i)=>{b.setAttribute('aria-selected',i===index?'true':'false');b.tabIndex=i===index?0:-1});document.querySelector('#day-panel').setAttribute('aria-labelledby',`day-tab-${index}`);document.querySelector('#day-label').textContent=`DAY ${String(index+1).padStart(2,'0')} · ${d.city}`;document.querySelector('#day-title').textContent=d.title;document.querySelector('#day-summary').textContent=d.summary;document.querySelector('#day-note').textContent=notes[index];document.querySelector('#timeline').innerHTML=d.events.map((e,i)=>{const p=place(e),t=type(e),key=`${index}-${i}`;return `<article class="event"><div class="event-top"><time class="event-time">${e[0]}</time><span class="category ${t[1]}">${t[0]}</span><label class="check-label"><input type="checkbox" data-event="${i}" ${visits[key]?'checked':''} aria-label="${e[1]} 완료">방문 체크</label></div><div class="event-card ${visits[key]?'checked':''}">${/왓아룬 관광|왓아룬 일몰/.test(e[1])?'<img class="event-picture" src="wat-arun.jpg" alt="강에서 바라본 왓아룬">':''}<div class="event-body"><h3>${e[1]}</h3>${p?`<span class="event-meta">${p[2]}</span>`:''}<p>${e[2]||'예정된 시간에 맞춰 여유롭게 준비해요.'}</p>${p?`<div class="event-links"><a class="button" target="_blank" rel="noreferrer" href="https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(p[1])}">▧ 지도</a><a class="button primary" target="_blank" rel="noreferrer" href="https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(p[1])}">➤ 길찾기</a></div>`:''}</div></div></article>`}).join('');document.querySelectorAll('[data-event]').forEach(el=>el.onchange=()=>{visits[`${selected}-${el.dataset.event}`]=el.checked;try{localStorage.setItem('thai-trip-visits',JSON.stringify(visits))}catch{storageOK=false}el.closest('.event').querySelector('.event-card').classList.toggle('checked',el.checked);progress()});let stops=d.summary.split(' → ');document.querySelector('#route-list').innerHTML=stops.map(s=>`<li>${s}</li>`).join('');document.querySelector('#night-number').textContent=`NIGHT ${String(index+1).padStart(2,'0')}`;document.querySelector('#night-place').textContent=index<2?'방콕 · 숙소 미정':index<5?'파타야 · 숙소 미정':index===5?'방콕 · 숙소 미정':index===6?'TG656 · 기내 숙박':'여행 마무리';document.querySelector('#stay-button').hidden=index===7;document.querySelector('#stay-button').textContent=index===6?'항공편 확인':'숙소 확인';document.querySelector('#previous').disabled=index===0;document.querySelector('#next').disabled=index===7;document.querySelector('#page-count').textContent=`${index+1} / 8 DAYS`;progress()}
function showView(){const name=location.hash.slice(1)||'schedule';const valid=['schedule','flights','stays','restaurants','food','info'].includes(name)?name:'schedule';document.querySelectorAll('.view').forEach(el=>el.hidden=el.id!==valid);document.querySelectorAll('[data-view]').forEach(el=>{el.classList.toggle('active',el.dataset.view===valid);if(el.dataset.view===valid)el.setAttribute('aria-current','page');else el.removeAttribute('aria-current')})}
document.querySelector('#previous').onclick=()=>{if(selected>0)render(selected-1)};document.querySelector('#next').onclick=()=>{if(selected<7)render(selected+1)};document.querySelector('#stay-button').onclick=()=>location.hash=selected===6?'flights':'stays';document.querySelector('#today').onclick=()=>{const now=new Date();const parts=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Bangkok',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(now);const get=t=>parts.find(x=>x.type===t).value;let i=get('year')==='2026'&&get('month')==='10'?Number(get('day'))-14:0;render(Math.max(0,Math.min(7,i)));location.hash='schedule';nav.children[selected].scrollIntoView({block:'nearest',inline:'nearest'})};
document.querySelector('#food-list').innerHTML=days.slice(0,7).map((d,i)=>{const meals=d.events.filter(e=>e[3]==='food'||/먹방/.test(e[1]));return `<article class="info-card"><span class="eyebrow">DAY ${String(i+1).padStart(2,'0')} · ${d.date}</span><h3>${d.city}</h3>${meals.map(e=>`<div class="food-item"><time>${e[0]}</time><span>${e[1]}<small>${e[2]}</small></span></div>`).join('')}<button class="button" data-day-link="${i}">이날 일정 보기 →</button></article>`}).join('');document.querySelectorAll('[data-day-link]').forEach(b=>b.onclick=()=>{render(Number(b.dataset.dayLink));location.hash='schedule'});window.addEventListener('hashchange',showView);render(0);showView();
